= Circle Stacker

A simple android game written in compose.

== Apk Signatures For Verifying Downloads From Github Releases

----
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

SHA-256: 776761e59c44b018e1838a2e2157f43176cd22d66454341fa7d6d84d5b1fb823
SHA-1: f79d1deeb486a9384e19b08f3797515ab5200a8f
MD5: fc617b5cb055ce78c78fe72550de1a07
-----BEGIN PGP SIGNATURE-----

iHUEARYIAB0WIQQyOd8AW98s0niYV69Z+EL3O68qjQUCaCykwgAKCRBZ+EL3O68q
jSDiAP4qOIbS1tQdfArDH3qtdeOO72fKZ0RLZVkIzN0qJj0UfgEAuJKuXHSYqgv2
jNIl84fmhKDJyPlxOp4B7wNRDEasuwg=
=eGyZ
-----END PGP SIGNATURE-----
----

== License

----
MIT License

Copyright (c) 2025 Andrew Reitz

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
----
