name: Android CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build with Gradle (using gradle/actions)
        uses: gradle/actions/setup-gradle@v3

      - name: Build project
        run: gradle build --no-daemon
