name: Web WASM Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Web WASM Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build WASM JS Browser Distribution
        run: ./gradlew wasmJsBrowserDistribution --no-daemon

      - name: Upload Web WASM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web.zip
          path: composeApp/build/dist/wasmJs/productionExecutable
